Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogIt.Data;
using BlogIt.Models;
using Microsoft.AspNetCore.Html;
using System.Net;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;
using HtmlAgilityPack;
using System.Reflection.Metadata;
using System.IO;
using System.Web;
using System.Data;

namespace BlogIt.Controllers
{
    [Authorize(Roles ="User")]
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BlogsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task GetData(List<Blog> blogs, Dictionary<string, UserProfie> userProfileDict, Dictionary<string, List<Comment>> CommentsDict)
        {
            // Gives userProfiles of each blog using blog id, to display userName and user profile pic
            // Gives Comments available on  each blog using blogid
            foreach (var blog in blogs)
            {
                var userProfile = await _context.UserProfiles.FirstOrDefaultAsync(x => x.UserId == blog.UserId);
                if (userProfile != null) userProfileDict[blog.UserId] = (UserProfie)userProfile;

                var comments = await _context.Comments.Where(c => c.BlogId == blog.Id).ToListAsync();

                CommentsDict[blog.Id] = comments;
                // To display userName and user profile pic of all users who commented on the blog 
                foreach (var comment in comments)
                {
                    if (!userProfileDict.ContainsKey(comment.UserId))
                    {
                        userProfile = await _context.UserProfiles.FirstOrDefaultAsync(x => x.UserId == comment.UserId);
                        if (userProfile != null) userProfileDict[comment.UserId] = (UserProfie)userProfile;
                    }
                }
            }
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            var currentUserId = userManager.GetUserId(this.User);

            var currentUser = await userManager.FindByIdAsync(currentUserId);

            // Get all blogs of current user and display it in his page
            var blogs = _context.Blogs.Include(b => b.BlogCategory).Include(b => b.User).Where(b=>b.User.Id==currentUserId).OrderByDescending(b => b.Date).ToList();

            // To store userProfiles of that blog id, to display userName and user profile pic in each comment
            var userProfileDict = new Dictionary<string, UserProfie>();

            // To store Comments of that blog id, to display userName and user profile pic in blogs
            var CommentsDict = new Dictionary<string, List<Comment>>();
            
            await GetData(blogs, userProfileDict, CommentsDict);
        
            ViewBag.UserProfiles = userProfileDict;
            ViewBag.Comments = CommentsDict;
            return View(blogs);
            
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }
  
            var blog = await _context.Blogs
                .Include(b => b.BlogCategory)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if(blog == null)
            {
                return NotFound();
            }

            // To store Comments of that blog id
            var CommentsDict = new Dictionary<string, List<Comment>>();
            var comments = await _context.Comments.Where(c => c.BlogId == blog.Id).ToListAsync();
            CommentsDict[blog.Id] = comments;

            // To store userProfiles of that blog id, to display userName and user profile pic in each comment
            var userProfileDict = new Dictionary<string, UserProfie>();
            foreach (var comment in comments)
            {
                var userProfile = await _context.UserProfiles.FirstOrDefaultAsync(x => x.UserId == comment.UserId);
                if(userProfile!=null) userProfileDict[comment.UserId] = (UserProfie)userProfile;
            }
            ViewBag.UserProfiles = userProfileDict;
            ViewBag.Comments = CommentsDict;
            return View(blog);
        }
        public async Task<string> SaveImage(IFormFile Pic)
        {
            string ImgPath = "";

            if (Pic != null && Pic.Length > 0)
            {
                // Generate a unique filename for the profile picture
                string fileName = Path.GetFileName(Pic.FileName);
                //string uniqueFileName = Guid.NewGuid().ToString() + "_" + fileName;
                string uniqueFileName = fileName;
                // Get the web root path
                string webRootPath = _webHostEnvironment.WebRootPath;

                // Combine the web root path and the "images" folder to get the full path to the destination folder
                string destinationFolderPath = Path.Combine(webRootPath, "images");

                // If the destination folder doesn't exist, create it
                if (!Directory.Exists(destinationFolderPath))
                {
                    Directory.CreateDirectory(destinationFolderPath);
                }

                // Combine the destination folder path and the unique filename to get the full path to the destination file
                string destinationFilePath = Path.Combine(destinationFolderPath, uniqueFileName);

                // Save the file to the destination path
                using (var stream = new FileStream(destinationFilePath, FileMode.Create))
                {
                    await Pic.CopyToAsync(stream);
                }

                // Update the user profile object with the URL of the saved image
                ImgPath = $"<img src=\"/images/{uniqueFileName}\" alt=\"Picture\" style=\"display: block; margin: 0 auto;\"/>";

            }
            return ImgPath;
        }
        // GET: Blogs/Create
        public IActionResult Create()
        {
            var currentUserId = userManager.GetUserId(this.User);
            ViewData["CategoryNames"] = new SelectList(_context.BlogCategories, "Name", "Name");
            ViewBag.UserId = currentUserId;
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,content,Date,UserId,CategoryId")] Blog blog,string CategoryName,string EditorContent, IFormFile Pic)
        {
            try
            {
                blog.Date = DateTime.Now;
                blog.CategoryId = _context.BlogCategories.Where(c => c.Name == CategoryName).Select(c => c.Id).FirstOrDefault();
                blog.content = SaveImage(Pic).Result + EditorContent;
                blog.UserId = userManager.GetUserId(this.User);
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(DBConcurrencyException)
            {
                return NotFound();
            }
        }

        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Blogs == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            ViewData["content"] = blog.content;
            ViewData["CategoryNames"] = new SelectList(_context.BlogCategories, "Name", "Name");
            ViewData["CurrentCategory"] = _context.BlogCategories.Where(c => c.Id == blog.CategoryId).Select(c => c.Name).FirstOrDefault();
            ViewBag.UserId = userManager.GetUserId(this.User);
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,content,Date,UserId,CategoryId")] Blog blog,string CategoryName,string EditorContent, IFormFile Pic)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            try
            {
                
                blog.Date = DateTime.Now;
                blog.CategoryId = _context.BlogCategories.Where(c => c.Name == CategoryName).Select(c => c.Id).FirstOrDefault();
                blog.content = SaveImage(Pic).Result + EditorContent;
                blog.UserId = userManager.GetUserId(this.User);
                _context.Update(blog);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BlogExists(blog.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

Controllers/FollowersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogIt.Data;
using BlogIt.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BlogIt.Controllers
{
    [Authorize(Roles = "User")]
    public class FollowersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public FollowersController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Followers
        public async Task<IActionResult> Followers()
        {
            // TO get followers of current user
            var currentUserId = _userManager.GetUserId(this.User);
            var applicationDbContext = _context.Followers.Include(f => f.User).Where(f=>f.UserId == currentUserId);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Following()
        {
            // To get the following list of current user
            var currentUserId = _userManager.GetUserId(this.User);
            var currentUser = await _userManager.FindByIdAsync(currentUserId);
            var applicationDbContext = _context.Followers.Include(f => f.User).Where(f => f.FollowerId == currentUserId);

            // Getting names of following users since I am not storing followingUserID as user foreignKey 
            // Only FollowerserId is refrencing to User as Foreign key
            foreach(var item in  await applicationDbContext.ToListAsync())
            {
                var itemUser = await _userManager.FindByIdAsync(item.UserId);
                //followingUsers.Add(itemUser);
                ViewData[item.UserId] = itemUser.UserName;
            }


            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Index(string userId)
        {
            // Using index to create a record in Followers table
            var currentUserId = _userManager.GetUserId(this.User);
            ViewData["FollowerId"] = new SelectList(_context.Users, "Id", "Id");
            var Follower = new Follower();
            Follower.UserId = userId;
            Follower.FollowerId = currentUserId;
            _context.Add(Follower);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        // GET: Followers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            // To remove a follower or to unfollow a following user and redirects to profile page
            if (id == null || _context.Followers == null)
            {
                return NotFound();
            }
            var follower = await _context.Followers.FindAsync(id);
            if (follower != null)
            {
                _context.Followers.Remove(follower);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index","UserProfies");
        }


        private bool FollowerExists(int id)
        {
          return (_context.Followers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/UserProfies/Details.cshtml
@*@model BlogIt.Models.UserProfie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserProfie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Interests)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Interests)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
*@
@model BlogIt.Models.UserProfie

<!DOCTYPE html>
<html>
<head>
    <title>Blogger Profile</title>
    <style>
        /* Style for the main container */
        .container {
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            box-sizing: border-box;
            font-family: Arial, sans-serif;
        }
        /* Style for the profile picture */
        .profile-pic {
            display: block;
            margin: 0 auto 20px;
            width: 200px;
            height: 200px;
            border-radius: 50%;
            object-fit: cover;
        }
        /* Style for the profile name */
        .profile-name {
            font-size: 36px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 10px;
        }
        /* Style for the profile description */
        .profile-desc, .profile-email {
            font-size: 20px;
            text-align: center;
            margin-bottom: 20px;
        }
        /* Style for the social media icons */
        .social-icons {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }

            .social-icons a {
                display: inline-block;
                width: 40px;
                height: 40px;
                margin: 0 10px;
                border-radius: 50%;
                background-color: #ccc;
                color: #fff;
                text-align: center;
                line-height: 40px;
                transition: background-color 0.3s ease;
            }

                .social-icons a:hover {
                    background-color: #666;
                }
        /* Style for the blog posts */
        .blog-posts {
            border-top: 1px solid #ccc;
            padding-top: 20px;
        }

            .blog-posts h2 {
                font-size: 24px;
                margin-bottom: 10px;
            }

            .blog-posts p {
                font-size: 16px;
                line-height: 1.5;
                margin-bottom: 20px;
            }

            .blog-posts a {
                font-size: 16px;
                color: #333;
                text-decoration: none;
                transition: color 0.3s ease;
            }

                .blog-posts a:hover {
                    color: #666;
                }

        img.facebook {
            width: 40px;
            height: 40px;
        }
    </style>
</head>

<body>
    <div style="text-align: right;" class="mb-2">
        <div style="float: right;">
            <div>
                @if (Model.UserId != ViewBag.currentUserId && (ViewBag.FollowingList == null || !ViewBag.FollowingList.Contains(Model.UserId)))
                {
                    <a asp-action="Index" asp-controller="Followers" asp-route-userId="@Model.UserId" style="text-decoration:none">Follow</a>
                }
            </div>
        </div>
    </div>
    <div class="container">
        <!-- Profile picture -->
        <img class="profile-pic" style="height:100px;width:100px" src="@Model.ProfilePic" alt="Profile picture" />

        <!-- Profile name and description -->
        <h1 class="profile-name">@Model.Name</h1> 
        <p class="profile-email">@Model.Email</p>
        <p class="profile-desc">@Model.Interests</p>
        <div class="profile-desc">
            <p>@Model.Description</p>
        </div>
        <!-- Social media icons -->
        <div class="social-icons">
            @if (!string.IsNullOrEmpty(Model.Facebook))
            {
                <a href="@Model.Facebook"><img class="facebook" style="height:40px;width:40px" src="/images/facebook.jpg"></a>
            }
            @if (!string.IsNullOrEmpty(Model.Twitter))
            {
                <a href="@Model.Twitter"><img class="Twitter" style="height:40px;width:40px" src="/images/Twitter.png"></a>
            }
            @if (!string.IsNullOrEmpty(Model.Instagram))
            {
                <a href="@Model.Instagram"><img class="instagram" style="height:40px;width:40px" src="/images/instagram.jpg"></a>
            }
            @if (!string.IsNullOrEmpty(Model.Youtube))
            {
                <a href="@Model.Youtube"><img class="YouTube" style="height:40px;width:40px" src="/images/YouTube.png"></a>
            }
        </div>
    </div>
    <div class="container">
        <h1 class="text-center">Blog List</h1>
        <hr />
        <div class="row">
            @foreach (var item in ViewBag.UserBlogs)
            {
                <div class="col-md-8 offset-md-2 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="text-center">@item.Title</h3>
                        </div>
                        <div class="card-body">
                            <p class="card-text text-muted" style="text-align:center;color:black">
                                <span class="label"></span>Category: @item.BlogCategory.Name
                                @*<span class="label"></span>@Html.DisplayFor(modelItem => item.User.UserName)*@
                                <span class="label"></span>Date: @item.Date
                            </p>
                            <p class="card-text">@Html.Raw(item.content)</p>

                        </div>
                        <div class="card-footer">
                                <form asp-action="CreateComment" asp-controller="Blogs" method="post">
                                    <div class="form-group">
                                        <textarea name="content" class="form-control" placeholder="Write a comment..."></textarea>
                                    </div>
                                    <br />
                                    <button type="submit" class="btn btn-primary" Style="background-color:indianred">Post</button>
                                    <input type="hidden" name="blogId" value="@item.Id" />
                                </form>
                            <hr />
                            <hr />
                            @{
                                var Comments = ViewBag.Comments[item.Id];
                            }
                            @if (Comments != null && Comments.Count != 0)
                            {
                                <h4>Comments:</h4>
                                @foreach (var comment in Comments)
                                {
                                    var commenterProfile = ViewBag.UserProfiles[comment.UserId];
                                    <div class="card mb-3">
                                        <div class="card-body">
                                            <div class="d-flex align-items-center">
                                                @if (!string.IsNullOrEmpty(commenterProfile.ProfilePic))
                                                {
                                                    <img src="@commenterProfile.ProfilePic" class="rounded-circle mr-2" width="40" height="40">
                                                }
                                                <p class="mb-0"><b>@commenterProfile.Name</b></p>
                                            </div>
                                            <p class="card-text">@comment.Content</p>
                                            <p class="card-text text-muted">@comment.Date.ToString("d MMM yyyy, h:mm tt")</p>
                                        </div>
                                    </div>
                                }
                            }
                            else
                            {
                                <p>No comments yet.</p>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>

Views/UserProfies/Index.cshtml
@model BlogIt.Models.UserProfie
@using System.Linq
<!DOCTYPE html>
<html>
<head>
    <title>Blogger Profile</title>
    <style>
        .container {
            display: flex;
            flex-wrap: wrap;
        }

        .profile {
            width: 30%;

        }

        .blogs {
            width: 200%;
            justify-content:center
        }
        /* Style for the profile picture */
        .profile-pic {
            display: block;
            margin: 0 auto 20px;
            width: 200px;
            height: 200px;
            border-radius: 50%;
            object-fit: cover;
        }

        /* Style for the profile name */
        .profile-name {
            font-size: 36px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 10px;
        }

        /* Style for the profile description */
        .profile-desc, .profile-email {
            font-size: 20px;
            text-align: center;
            margin-bottom: 20px;
        }

        /* Style for the social media icons */
        .social-icons {
            display: flex;
            justify-content: center;
            margin-bottom: 20px;
        }

            .social-icons a {
                display: inline-block;
                width: 40px;
                height: 40px;
                margin: 0 10px;
                border-radius: 50%;
                background-color: #ccc;
                color: #fff;
                text-align: center;
                line-height: 40px;
                transition: background-color 0.3s ease;
            }

                .social-icons a:hover {
                    background-color: #666;
                }

        /* Style for the blog posts */
        .blog-posts {
            border-top: 1px solid #ccc;
            padding-top: 20px;
        }

            .blog-posts h2 {
                font-size: 24px;
                margin-bottom: 10px;
            }

            .blog-posts p {
                font-size: 16px;
                line-height: 1.5;
                margin-bottom: 20px;
            }

            .blog-posts a {
                font-size: 16px;
                color: #333;
                text-decoration: none;
                transition: color 0.3s ease;
            }

            .blog-posts a:hover {
                color: #666;
            }

        .label {
            margin-right: 70px;
        }
    </style>

</head>


<body>
    <div style="text-align: right;" class="mb-2">
        <div style="float: right;">
            <div>
                <a asp-action="Index" asp-controller="Blogs" class="btn btn-primary" style="background-color:indianred">My Blogs</a>

            </div>
        </div>
    </div>
    <div class="container row" style="margin-top:10px">
        <div class="Profile col" style="margin-top:20px">
            <!-- Profile picture -->
            <img class="profile-pic" style="height:100px;width:100px" src="@Model.ProfilePic" alt="Profile picture" />

            <!-- Profile name and description -->
            <h1 class="profile-name">@Model.Name</h1>
            <p class="profile-email">@Model.Email</p>
            <p class="profile-desc">@Model.Interests</p>
            <div class="profile-desc">
                <p>@Model.Description</p>
            </div>
         
            <!-- Social media icons -->
            <div class="social-icons">
                @if (!string.IsNullOrEmpty(Model.Facebook))
                {
                    <a href="@Model.Facebook"><img class="facebook" style="height:40px;width:40px" src="/images/facebook.jpg"></a>
                }
                @if (!string.IsNullOrEmpty(Model.Twitter))
                {
                    <a href="@Model.Twitter"><img class="Twitter" style="height:40px;width:40px" src="/images/Twitter.png"></a>
                }
                @if (!string.IsNullOrEmpty(Model.Instagram))
                {
                    <a href="@Model.Instagram"><img class="instagram" style="height:40px;width:40px" src="/images/instagram.jpg"></a>
                }
                @if (!string.IsNullOrEmpty(Model.Youtube))
                {
                    <a href="@Model.Youtube"><img class="YouTube" style="height:40px;width:40px" src="/images/YouTube.png"></a>
                }
                <div class="profile-footer">
                    <a asp-action="Edit" asp-route-id="@Model.Id" style="text-decoration:none">Edit Profile</a>
                </div>
            </div>
            <div class="row">
                <div class="col" style="margin-left:60px">
                    <a asp-action="Followers" asp-controller="Followers" style="text-decoration:none">Followers</a>
                </div>
                <div class="col">
                    <a asp-action="Following" asp-controller="Followers" style="text-decoration:none">Following</a>
                </div>
            </div>
        </div>
        <div class="blogs col">
            <div class="row">
                @if (ViewBag.BlogListTop2 == null)
                {
                    <div class="col-md-8 offset-md-2 mb-4">
                        <div class="card" style="width: 600px; height: 300px;">
                            <div class="card-header">
                                <p style="text-align:center"><i>....No Blogs posted....</i></p>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <h5 class="text-center" style="-ms-text-underline-position:50px;padding-left:200px">Latest Blogs</h5>
                @foreach (var item in ViewBag.BlogListTop2)
                {
                    <a href="@Url.Action("Details", "Blogs", new { id = item.Id })" style="text-decoration: none; color: inherit;">
                        <div class="col-md-8 offset-md-2 mb-4">
                            <div class="card" style="width: 600px; height: 300px;">
                                <div class="card-header">
                                    <h3 class="text-center">@item.Title</h3>
                                </div>
                                <div class="card-body">
                                    <p class="card-text text-muted">
                                        <span class="label"></span>Category: @item.BlogCategory.Name
                                        <span class="label"></span>Date: @item.Date
                                    </p>
                                </div>
                            </div>
                        </div>
                    </a>
                    
                }
                }
            </div>
        </div>
        
       </div>
        
    </body>
</html>